[profile.default]
src = 'src'
out = 'out'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
fuzz_runs = 1_000
libs = ['lib']
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "foundry-huff=lib/foundry-huff/src/",
]
gas_reports = ['*']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config